version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/website
    sync: true
    matcher:
      files: "website/**"

  - label: area/adapters
    sync: true
    matcher:
      files: "adapters/**"

  - label: area/salmon
    sync: true
    matcher:
      files: "packages/salmon/**"

  - label: area/salmon-fetch
    sync: true
    matcher:
      files: "packages/salmon-fetch/**"

  - label: area/salmon-filter
    sync: true
    matcher:
      files: "packages/salmon-filter/**"

  - label: area/salmon-wallet
    sync: true
    matcher:
      files: "packages/salmon-wallet/**"
