name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - name: Upgrade dependencies
        run: |
          npx npm-check-updates -l m -u --deep --target newest --pre -f "/^defichain|@defichain\/.+/" -x "/^@defichain\/(oracle-adapters|salmon)-.+/" \
          | grep -q 'Run npm install to install new versions' && \
          npm i

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: Bump @defichain/* dependencies
          commit-message: Bump @defichain/* dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/*` dependencies to the latest release.
          branch: defichain-bot/bump-defichain-deps
