name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 16

      - run: npx npm-check-updates -l m -u --deep --target newest --pre -f "/^defichain|@defichain\/.+/" -x "/^@defichain\/(oracle-adapters|salmon)-.+/"

      - name: Upgrade dependencies
        run: |
          if ! git diff-index --quiet HEAD; then
            npm i
          else
            echo "no file has been changed"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          token: ${{ secrets.JELLYFISHSDK_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: Jellyfish Bot <bots+github-jellyfish@birthday.dev>
          author: Jellyfish Bot <bots+github-jellyfish@birthday.dev>
          title: "bump(deps): @defichain/* dependencies"
          commit-message: Bump @defichain/* dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/*` dependencies to the latest release.
          branch: defichain-bot/bump-defichain-deps
