name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236
        with:
          node-version: 16

      - run: npx npm-check-updates -l m -u --deep --target newest --pre -f "/^defichain|@defichain\/.+/" -x "/^@defichain\/(oracle-adapters|salmon)-.+/"

      - name: Upgrade dependencies
        run: |
          if ! git diff-index --quiet HEAD; then
            npm i
          else
            echo "no file has been changed"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: Bump @defichain/* dependencies
          commit-message: Bump @defichain/* dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/*` dependencies to the latest release.
          branch: defichain-bot/bump-defichain-deps
