name: Sync Repo to JellyfishSDK

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@3832fe8e2be32372e1b3970bbae8e7079edeec88
      with:
        source_repo: "JellyfishSDK/oracle-adapters"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sync_tags: "true"
