name: Publish

on:
  release:
    types: [ published ]

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    environment: NPM Release
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: '15'

      - uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/^[0-9]+\.[0-9]+\.[0-9]+$/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string

      - run: npm ci
      - run: npm run build
      - run: npm run version:set ${{ steps.version.outputs.result }}

      - name: find and replace peerDependencies # because lerna doesn't update peers deps
        run: |
          find packages/*/package.json adapters/package.json -type f -exec sed -i 's#    "@defichain/salmon-core": "0.0.0"#    "@defichain/salmon-core": "${{ steps.version.outputs.result }}"#g' {} \;

      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run publish:latest
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
