name: Publish

on:
  release:
    types: [ published ]

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    environment: NPM Release
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16

      - uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/^[0-9]+\.[0-9]+\.[0-9]+$/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string

      - run: npm ci
      - run: npm run build
      - run: npm run version:set ${{ steps.version.outputs.result }}

      # Because lerna doesn't update peers deps, although using it "wrongly" this behavior ensures all deps are aligned.
      - name: find and replace peerDependencies
        run: |
          find packages/*/package.json adapters/package.json -type f -exec sed -i 's#    "@defichain/salmon-core": "0.0.0"#    "@defichain/salmon-core": "^${{ steps.version.outputs.result }}"#g' {} \;

      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run publish:latest
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
